apiVersion: v1
kind: Service
metadata:
  name: contosoair
  namespace: contosoair
spec:
  type: LoadBalancer
  ports:
  - port: 32325
    targetPort: 8080
  selector:
    app: contosoair
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contosoair
  namespace: contosoair
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contosoair
  template:
    metadata:
      labels:
        app: contosoair
    spec:
      containers:
      - name: contosoair
        image: acrtardemo.azurecr.io/contosoair:latest
        ports:
        - containerPort: 8080
